# Generated by Django 3.2.6 on 2021-09-25 12:24

from django.db import migrations
import oauth2.managers


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0004_auto_20210925_1101'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', oauth2.managers.OAuth2Manager()),
            ],
        ),
    ]
